#!/bin/bash
. .scripts-common
check_create_cd ".build-dev"

#export VELOCYPACK_INCLUDE_DIR=~/PROJECT/4.cache/arangodbcache/velocypack/include
#export VELOCYPACK_LIBRARY=~/PROJECT/4.cache/arangodbcache/velocypack/lib

#cmake -DCMAKE_BUILD_TYPE=Debug -DFUERTE_TESTS=ON -DFUERTE_EXAMPLES=ON .. && make -j $(nproc) && \
cmake $CMAKE_ARGS -DCMAKE_BUILD_TYPE=Debug -DFUERTE_TESTS=ON .. && 
    make -j $(nproc) && \
    ctest --output-on-failure --verbose

